LATEST_VERSION=$(curl -s https://api.github.com/repos/Cog-Creators/Lavalink-Jars/releases/latest | grep 'tag_name' | cut -d\" -f4)
echo Downloading Lavalink.jar version $LATEST_VERSION...
curl -LJO "https://github.com/Cog-Creators/Lavalink-Jars/releases/download/$LATEST_VERSION/Lavalink.jar"
echo Lavalink.jar is downloaded...
echo Starting Lavalink...
java -jar Lavalink.jar &
